import type { Metadata } from "next";
import { Nunito, M_PLUS_1p} from "next/font/google";
import {ClerkProvider} from '@clerk/nextjs'
import "./globals.css";

const font = Nunito({
  subsets: ["latin"],
});





export const metadata: Metadata = {
  title: "Otta Sensei",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${font.className}`}>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
